/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Profile;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-19T19:22:40.372Z")

@Api(value = "profile", description = "the profile API")
@RequestMapping(value = "/index")
public interface ProfileApi {

    @ApiOperation(value = "Edit user's profile", nickname = "edditProfile", notes = "User must be loged in.", tags={ "profile", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Incorrect data"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/profile/edditProfile/{userId}",
        produces = {"application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Void> edditProfile(@ApiParam(value = "User can only edit itself.",required=true) @PathVariable("userId") String userId,@ApiParam(value = "Contain profile in JSON" ,required=true )  @Valid @RequestBody Profile profile) {

        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
